import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { MaterialModule } from '@/_modules/material.module';
import { Ng2SearchPipeModule } from 'ng2-search-filter';
import { CurrencyMaskModule } from 'ng2-currency-mask';
import { NgSelectModule } from '@ng-select/ng-select';
import { ManagerRoutingModule } from './manager-routing.module';
import { RoleComponent } from './role';
import { AlertModule } from '@/_components/alert/alert.module';
import { FileUploadModule } from 'ng2-file-upload';
import { NgxSpinnerModule } from 'ngx-spinner';
import { ReportTallyComponent, ContrastReportComponent, InventoryReportComponent, ActionReportComponent, DetailReportComponent } from './report';
import { WarehouseManageComponent, WarehouseOutputComponent, ChiTietXuatKhoComponent, DuyetXuatKhoComponent, WarehouseInputComponent } from './warehouse';
import { TallyPackageComponent, KiemDemThungComponent, WarehouseDocumentComponent, ACQTComponent, BoxCloseComponent, BoxExportComponent, BoxDownloadComponent, ConfirmCompleteComponent } from './tally';
import { ReceiverInforComponent, RequestTicketManagementComponent, AllocationACQTComponent,ReportACQTComponent, SendEmailComponent,
         ApproveTicketComponent, TicketManageComponent } from './form';
import { DischargeWarehouseComponent } from './discharge-warehouse/discharge-warehouse.component';
import { CreateFailDischargeWarehouseComponent, CreateReachDischargeWarehouseComponent, EditDischargeReachInforComponent, EditDischargeFailInforComponent,
        ApproveDischargeWarehouseComponent, QrcodeDischargeComponent, DetailInforComponent } from './discharge-warehouse/dialog';
import { DialogDisapproveDischargeComponent } from './discharge-warehouse/dialog/approve-discharge-warehouse/index';
import { ContrastObjectComponent, ContrastInforManagementComponent, ApproveInforWarehouseComponent } from './input-warehouse-unit';
import { DialogAceptWarehouseComponent, DialogApproveWarehouseComponent } from './input-warehouse-unit/approve-infor-warehouse/dialog';
import { ContrastInforACQTComponent, DetailContrastComponent } from './input-warehouse-unit/contrast-infor-management/dialog';
import { DetailReqTicketReportComponent } from './form/report-acqt/dialog'
import { DialogACQTComponent, DialogNotificateComponent } from './tally/acqt';
import { DialogBoxCloseComponent, EditBoxComponent, InputWarehouseComponent, PrintBoxComponent, DialogAceptComponent } from './tally/box';
import { EditCategoryComponent, CreateCategoryComponent, DetailCategoryComponent } from './category/dialog';
import { EditPackageComponent, CreatePackageComponent, DetailPackageComponent, PrintLabelPackageComponent } from './tally/package';
import { CreateInforReceiverComponent, EditInforReceiverComponent, DetailInforReceiverComponent } from './form/receiver-infor/dialog';
import { CreateInforTicketComponent, DetailInforTicketComponent, EditInforTicketComponent, QrcodeTicketComponent } from './form/ticket-manage/dialog';
import { DetailInforTicketWarehouseComponent, EditInforTicketWarehouseComponent } from './form/approve-ticket/dialog';
import { DialogDisapproveComponent } from './form/approve-ticket/dialog/detail-infor-ticket-warehouse';
import { DetailSeriComponent } from './warehouse/warehouse-manage/dialog';
import { DetailContrastReportComponent } from './report/contrast-report/dialog';
import { DetailInventoryReportComponent } from './report/inventory-report/dialog';
import { DialogDetailReportComponent } from './report/detail-report/dialog';
import { DetailActionReportComponent } from './report/action-report/dialog';
import { CreateReqTicketComponent, EditReqTicketComponent, DetailReqTicketComponent, ApproveReqTicketComponent } from './form/request-ticket-management/dialog';
import { ApproveAllocationACQTComponent, DetailAllocationACQTComponent, DialogAceptTicketComponent } from './form/allocaton-acqt/dialog';
import { OnlyNumberDirective } from '@/only-number.directive';
import { DialogAceptERPComponent, DialogApproveComponent } from './tally/box/boxdownload/dialog';
import { DialogConfirmComponent, DialogDetailBoxComponent } from './tally/box/tally-box/dialog';
import { DialogApproveTallyComponent } from './tally/box/confirm-complete/dialog';
import { DialogDetailCostComponent } from './tally/box/boxexport/dialog';
import { CategoryComponent } from './category/category.component';
import { OrderModule } from 'ngx-order-pipe';
import { NgxLoadingModule, ngxLoadingAnimationTypes } from 'ngx-loading';
import { ConfirmationPopoverModule } from 'angular-confirmation-popover';
import { UpdateContrastInforACQTComponent } from './input-warehouse-unit/contrast-infor-management/dialog/update-contrast-infor-acqt/update-contrast-infor-acqt.component';

@NgModule({
    imports: [
        OrderModule,
        CommonModule,
        CurrencyMaskModule,
        FormsModule,
        MaterialModule,
        ManagerRoutingModule,
        ReactiveFormsModule,
        Ng2SearchPipeModule,
        FileUploadModule,
        AlertModule,
        NgxSpinnerModule,
        NgSelectModule,
        NgxLoadingModule.forRoot({
          animationType: ngxLoadingAnimationTypes.circleSwish,
          backdropBackgroundColour: 'rgba(0,0,0,0.1)',
          primaryColour: '#ffffff',
          secondaryColour: '#ffffff',
          tertiaryColour: '#ffffff'
        }),
        ConfirmationPopoverModule.forRoot({
          confirmButtonType: 'danger' // set defaults here
        })
    ],
    exports: [
        RoleComponent,
        ReportTallyComponent,
        ContrastReportComponent, 
        DetailContrastReportComponent,
        InventoryReportComponent, 
        DetailInventoryReportComponent,
        ActionReportComponent,
        DetailActionReportComponent, 
        DetailReportComponent,
        DialogDetailReportComponent,
        WarehouseManageComponent,
        WarehouseOutputComponent,
        ChiTietXuatKhoComponent,
        DuyetXuatKhoComponent,
        TallyPackageComponent,
        KiemDemThungComponent,
        WarehouseDocumentComponent,
        WarehouseInputComponent,
        ReceiverInforComponent,
        DialogACQTComponent,
        DialogNotificateComponent,
        DialogBoxCloseComponent,
        CategoryComponent,
        EditCategoryComponent,
        CreateCategoryComponent,
        DetailCategoryComponent,
        EditPackageComponent,
        CreatePackageComponent,
        DetailPackageComponent,
        EditBoxComponent,
        CreateInforReceiverComponent,
        EditInforReceiverComponent,
        DetailInforReceiverComponent,
        RequestTicketManagementComponent,
        CreateReqTicketComponent,
        EditReqTicketComponent,
        DetailReqTicketComponent,
        ApproveReqTicketComponent,
        AllocationACQTComponent,
        ApproveAllocationACQTComponent,
        DetailAllocationACQTComponent,
        DialogAceptTicketComponent,
        ReportACQTComponent,
        SendEmailComponent,
        ApproveTicketComponent,
        TicketManageComponent,
        InputWarehouseComponent,
        PrintLabelPackageComponent,
        // PrintNhanGoiComponent,
        PrintBoxComponent,
        ACQTComponent,
        BoxCloseComponent,
        RoleComponent,
        BoxExportComponent,
        OnlyNumberDirective,
        BoxDownloadComponent,
        ConfirmCompleteComponent,
        DialogApproveTallyComponent,
        DialogDetailCostComponent,
        DialogAceptComponent,
        DialogAceptERPComponent,
        DialogApproveComponent,
        DialogConfirmComponent,
        DialogDetailBoxComponent,
        CreateInforTicketComponent,
        DetailInforTicketComponent,
        EditInforTicketComponent,
        QrcodeTicketComponent,
        DetailInforTicketWarehouseComponent,
        EditInforTicketWarehouseComponent,
        DetailSeriComponent,
        DischargeWarehouseComponent,
        CreateFailDischargeWarehouseComponent, 
        CreateReachDischargeWarehouseComponent,
        EditDischargeReachInforComponent, 
        EditDischargeFailInforComponent,
        ApproveDischargeWarehouseComponent, 
        DialogDisapproveDischargeComponent,
        DialogDisapproveComponent,
        QrcodeDischargeComponent,
        DetailInforComponent,
        ContrastObjectComponent, 
        ContrastInforManagementComponent, 
        ApproveInforWarehouseComponent,
        DialogAceptWarehouseComponent, 
        DialogApproveWarehouseComponent,
        ContrastInforACQTComponent, 
        UpdateContrastInforACQTComponent,
        DetailContrastComponent,
        DetailReqTicketReportComponent
    ],
    declarations: [
        RoleComponent,
        ReportTallyComponent,
        ContrastReportComponent, 
        DetailContrastReportComponent,
        InventoryReportComponent, 
        DetailInventoryReportComponent,
        ActionReportComponent, 
        DetailActionReportComponent, 
        DetailReportComponent,
        DialogDetailReportComponent,
        WarehouseManageComponent,
        WarehouseOutputComponent,
        ChiTietXuatKhoComponent,
        DuyetXuatKhoComponent,
        TallyPackageComponent,
        KiemDemThungComponent,
        WarehouseDocumentComponent,
        WarehouseInputComponent,
        ReceiverInforComponent,
        DialogACQTComponent,
        DialogNotificateComponent,
        DialogBoxCloseComponent,
        CategoryComponent,
        EditCategoryComponent,
        CreateCategoryComponent,
        DetailCategoryComponent,
        EditPackageComponent,
        CreatePackageComponent,
        DetailPackageComponent,
        EditBoxComponent,
        CreateInforReceiverComponent,
        EditInforReceiverComponent,
        DetailInforReceiverComponent,
        RequestTicketManagementComponent,
        CreateReqTicketComponent,
        EditReqTicketComponent,
        DetailReqTicketComponent,
        ApproveReqTicketComponent,
        AllocationACQTComponent,
        ApproveAllocationACQTComponent,
        DetailAllocationACQTComponent,
        DialogDisapproveComponent,
        DialogAceptTicketComponent,
        ReportACQTComponent,
        SendEmailComponent,
        ApproveTicketComponent,
        TicketManageComponent,
        InputWarehouseComponent,
        PrintLabelPackageComponent,
        // PrintNhanGoiComponent,
        PrintBoxComponent,
        ACQTComponent,
        BoxCloseComponent,
        RoleComponent,
        BoxExportComponent,
        OnlyNumberDirective,
        BoxDownloadComponent,
        ConfirmCompleteComponent,
        DialogApproveTallyComponent,
        DialogDetailCostComponent,
        DialogAceptComponent,
        DialogAceptERPComponent,
        DialogApproveComponent,
        DialogConfirmComponent,
        DialogDetailBoxComponent,
        CreateInforTicketComponent,
        DetailInforTicketComponent,
        EditInforTicketComponent,
        QrcodeTicketComponent,
        DetailInforTicketWarehouseComponent,
        EditInforTicketWarehouseComponent,
        DetailSeriComponent,
        DischargeWarehouseComponent,
        CreateFailDischargeWarehouseComponent, 
        CreateReachDischargeWarehouseComponent,
        EditDischargeReachInforComponent, 
        EditDischargeFailInforComponent,
        ApproveDischargeWarehouseComponent, 
        DialogDisapproveDischargeComponent,
        QrcodeDischargeComponent,
        DetailInforComponent,
        ContrastObjectComponent, 
        ContrastInforManagementComponent, 
        ApproveInforWarehouseComponent,
        DialogAceptWarehouseComponent, 
        DialogApproveWarehouseComponent,
        ContrastInforACQTComponent, 
        UpdateContrastInforACQTComponent,
        DetailContrastComponent,
        DetailReqTicketReportComponent
    ],
    entryComponents: [
        ReportTallyComponent,
        ContrastReportComponent, 
        DetailContrastReportComponent,
        InventoryReportComponent, 
        DetailInventoryReportComponent,
        ActionReportComponent,
        DetailActionReportComponent,  
        DetailReportComponent,
        DialogDetailReportComponent,
        WarehouseManageComponent,
        WarehouseOutputComponent,
        ChiTietXuatKhoComponent,
        DuyetXuatKhoComponent,
        TallyPackageComponent,
        KiemDemThungComponent,
        WarehouseDocumentComponent,
        WarehouseInputComponent,
        ReceiverInforComponent,
        DialogACQTComponent,
        DialogNotificateComponent,
        DialogBoxCloseComponent,
        EditCategoryComponent,
        CreateCategoryComponent,
        DetailCategoryComponent,
        EditPackageComponent,
        CreatePackageComponent,
        DetailPackageComponent,
        EditBoxComponent,
        CreateInforReceiverComponent,
        EditInforReceiverComponent,
        DetailInforReceiverComponent,
        RequestTicketManagementComponent,
        CreateReqTicketComponent,
        EditReqTicketComponent,
        DetailReqTicketComponent,
        ApproveReqTicketComponent,
        AllocationACQTComponent,
        ApproveAllocationACQTComponent,
        DetailAllocationACQTComponent,
        DialogAceptTicketComponent,
        InputWarehouseComponent,
        PrintLabelPackageComponent,
        // PrintNhanGoiComponent,
        PrintBoxComponent,
        ACQTComponent,
        BoxCloseComponent,
        RoleComponent,
        BoxExportComponent,
        BoxDownloadComponent,
        ConfirmCompleteComponent,
        DialogApproveTallyComponent,
        DialogDetailCostComponent,
        DialogAceptComponent,
        DialogAceptERPComponent,
        DialogApproveComponent,
        DialogConfirmComponent,
        DialogDetailBoxComponent,
        CreateInforTicketComponent,
        DetailInforTicketComponent,
        EditInforTicketComponent,
        QrcodeTicketComponent,
        DetailInforTicketWarehouseComponent,
        EditInforTicketWarehouseComponent,
        DetailSeriComponent,
        DischargeWarehouseComponent,
        CreateFailDischargeWarehouseComponent, 
        CreateReachDischargeWarehouseComponent,
        EditDischargeReachInforComponent, 
        EditDischargeFailInforComponent,
        ApproveDischargeWarehouseComponent, 
        DialogDisapproveDischargeComponent,
        DialogDisapproveComponent,
        QrcodeDischargeComponent,
        DetailInforComponent,
        ContrastObjectComponent, 
        ContrastInforManagementComponent, 
        ApproveInforWarehouseComponent,
        DialogAceptWarehouseComponent, 
        DialogApproveWarehouseComponent,
        ContrastInforACQTComponent, 
        UpdateContrastInforACQTComponent,
        DetailContrastComponent,
        DetailReqTicketReportComponent
    ]
})
export class ManagerModule { }
